In [2]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)



Mounted at /content/drive


In [4]:
import pandas as pd


In [5]:
df=pd.read_csv('/content/drive/MyDrive/fake-news/train.csv')

In [6]:
df.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [7]:
df=df.dropna()

In [8]:
#independent feature
X=df.drop('label',axis=1)

In [9]:
#label
y=df['label']

In [10]:

y.value_counts()

0    10361
1     7924
Name: label, dtype: int64

In [11]:
X.shape

(18285, 4)

In [12]:
y.shape

(18285,)

In [13]:
import tensorflow as tf

In [14]:

tf.__version__

'2.5.0'

In [15]:

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [16]:
### Vocabulary size
voc_size=5000

In [17]:

messages=X.copy()

In [18]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [19]:

messages.reset_index(inplace=True)

In [20]:

import nltk
import re
from nltk.corpus import stopwords

In [21]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [22]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [23]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [24]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[4422, 4441, 1978, 3060, 1847, 1703, 1924, 80, 2345, 2516],
 [2688, 1254, 2098, 2818, 2239, 2762, 1061],
 [3171, 3222, 4273, 3817],
 [210, 4577, 1325, 3305, 3433, 680],
 [2788, 2239, 1264, 4434, 587, 3080, 2239, 609, 4726, 2647],
 [3284,
  236,
  490,
  2619,
  729,
  928,
  4662,
  4066,
  300,
  4731,
  976,
  4699,
  449,
  1121,
  1061],
 [3529, 4439, 2820, 4999, 4530, 1603, 2567, 1980, 1639, 4029, 2012],
 [4374, 4383, 2385, 890, 1122, 3200, 928, 1803, 1639, 4029, 2012],
 [3145, 4836, 4920, 4729, 4053, 4494, 49, 843, 928, 2143],
 [14, 1869, 4712, 270, 2134, 2178, 516, 271],
 [449, 2308, 3239, 3647, 46, 2658, 2410, 604, 598, 1520, 2909],
 [3305, 2661, 1847, 4494, 928, 1122],
 [1846, 2774, 4425, 388, 3495, 248, 2407, 2726, 704],
 [3759, 2918, 4234, 3784, 3749, 4321, 3049, 1639, 4029, 2012],
 [868, 663, 1054, 1482, 2630, 1639, 4029, 2012],
 [4258, 3689, 1835, 1023, 2962, 1456, 2517, 4435, 1402, 3328],
 [3745, 1229, 1254],
 [2817, 3555, 628, 260, 928, 3549, 4489, 1061],
 [2399, 4084, 

In [25]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...   80 2345 2516]
 [   0    0    0 ... 2239 2762 1061]
 [   0    0    0 ... 3222 4273 3817]
 ...
 [   0    0    0 ... 1639 4029 2012]
 [   0    0    0 ...  341 3246 4266]
 [   0    0    0 ... 2233 4544 2375]]


In [26]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 4422,
       4441, 1978, 3060, 1847, 1703, 1924,   80, 2345, 2516], dtype=int32)

In [28]:

## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
lstm_1 (LSTM)                (None, 100)               56400     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [29]:
## Creating model
embedding_vector_features=40
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100)))
model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
bidirectional (Bidirectional (None, 200)               112800    
_________________________________________________________________
dropout (Dropout)            (None, 200)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 201       
Total params: 313,001
Trainable params: 313,001
Non-trainable params: 0
_________________________________________________________________
None


In [30]:
len(embedded_docs),y.shape

(18285, (18285,))

In [31]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [32]:

X_final.shape,y_final.shape

((18285, 20), (18285,))

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [34]:
### Finally Training
model1.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 14s 53ms/step - loss: 0.2940 - accuracy: 0.8633 - val_loss: 0.2011 - val_accuracy: 0.9167
Epoch 2/10
192/192 [==============================] - 9s 47ms/step - loss: 0.1406 - accuracy: 0.9460 - val_loss: 0.2122 - val_accuracy: 0.9162
Epoch 3/10
192/192 [==============================] - 9s 47ms/step - loss: 0.1038 - accuracy: 0.9629 - val_loss: 0.2254 - val_accuracy: 0.9143
Epoch 4/10
192/192 [==============================] - 9s 47ms/step - loss: 0.0802 - accuracy: 0.9716 - val_loss: 0.2556 - val_accuracy: 0.9123
Epoch 5/10
192/192 [==============================] - 9s 47ms/step - loss: 0.0541 - accuracy: 0.9815 - val_loss: 0.3244 - val_accuracy: 0.9110
Epoch 6/10
192/192 [==============================] - 9s 47ms/step - loss: 0.0362 - accuracy: 0.9891 - val_loss: 0.4070 - val_accuracy: 0.9087
Epoch 7/10
192/192 [==============================] - 9s 48ms/step - loss: 0.0275 - accuracy: 0.9917 - val_loss: 0.4340 - val_accuracy: 0.911

In [35]:
y_pred1=model1.predict_classes(X_test)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [36]:
from sklearn.metrics import confusion_matrix

In [37]:
confusion_matrix(y_test,y_pred1)

array([[3071,  348],
       [ 196, 2420]])

In [38]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred1)

0.9098591549295775

In [39]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.94      0.90      0.92      3419
           1       0.87      0.93      0.90      2616

    accuracy                           0.91      6035
   macro avg       0.91      0.91      0.91      6035
weighted avg       0.91      0.91      0.91      6035

